language: java
jdk:
- oraclejdk8
sudo: false
install: true
git:
  depth: 3
script: mvn clean verify
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: 848f50e7-cd6c-44c9-a81f-9b86e5ca4932
  app:
    master: continuousdelivery
  on:
    repo: sveen12/spring-boot-docker-mysql